[package]
name = "eko-gc"
version = "0.0.3"
edition = "2018"

authors = ["Ravern Koh <ravernkoh@gmail.com>"]
description = "Scoped garbage collection"
readme = "../README.md"
license = "AGPL-3.0"

[dependencies]
